### PR TITLE
Hide profile when not logged in, fixes #164

### LINKED ISSUE #164: Show Profile option only when the user is logged in
## Current behavior
Right now, the "Profile" button on the side menu is shown even when the user isn't signed in. When we try to open the profile a toast is shown saying that "You need to login first".

## Required behavior
Only show the button when the user is signed in.

### PR DESCRIPTION
**Pull request by kartikarora**
Fixes #164 
Changes: 
- Added visibility settings for Profile option in the navigation menu of HomeActivity.java
- Fixed String comparison for login/logout in DrawerNavigator.java

Screenshots for the change:
device-2018-10-18-203748

### CODE REVIEW

**Review by dr0pdb — CHANGES_REQUESTED** [review]
Thanks for the PR. Merging another PR led to conflicts. Please resolve them.

Few points:
1. Please work on issues that aren't claimed by others.
2. It would be great if you can move the Log In button before the "Device settings" and "Suggestions" button.

**Comment by kartikarora** [comment]
Apologies for hijacking it, but in my defence, it had been 2 hours since the claim and there was nothing pushed. Only then I created a fork and worked on it.

**Comment by dr0pdb** [comment]
@kartikarora Yeah it's alright. I would suggest you wait for at least 3-4 days. 2 Hours is too small a time frame.

Please resolve the conflicts :)

**Comment by kartikarora** [comment]
@srv-twry Fixed in #170

**Comment by dr0pdb** [comment]
@kartikarora You should learn how to resolve merge conflicts in the same PR itself otherwise you'll face a lot of problems in the future. Please learn it. :)

**Pull request closed without merging**
