### PR TITLE
fix: Fixed the package structure for the Coding-Calendar

### PR DESCRIPTION
**Pull request by dr0pdb**
Earlier package structure was according to the ```MVP``` pattern.
But now considering the decision to stick to the usual pattern, this change was necessary.

### CODE REVIEW

**Comment by dr0pdb** [comment]
@chiragw15 @taeven @jtatia  Kindly review :smile:

**Comment by chiragw15** [comment]
>But now considering the decision to stick to the usual pattern, this change was necessary.

We finally decided on MVP, right? I don't remember.

**Comment by dr0pdb** [comment]
@chiragw15 Yes we did on the ```Whatsapp``` group but in the final meeting with @taeven  (You weren't there) , we decided to revert back to the normal pattern since it was deemed  easier and MVP was pretty hard to implement specially for beginners.

**Review by chiragw15 — APPROVED** [review]
Okay. Cool then

**Pull request merged**
