### PR TITLE
Loggin

### LINKED ISSUE #55: Use Timber for logging
**Actual Behaviour**

Right now we are using the default logging component provided by the Android SDK.

**Expected Behaviour**

We should use Timber for logging because it's very popular and is the industry standard.
Refactor all logging statements(if any) to use Timber 

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by jafjdev**
Implementation of Timber working.
We're not using Log anymore.

Fix #55

Changes:

We're using Timber instead of Log.
https://github.com/JakeWharton/timber

### CODE REVIEW

**Comment by dr0pdb** [comment]
@jafjdev After merging your other PR, you have merge conflicts in this one. Please resolve them :)

**Comment by jafjdev** [comment]
@srv-twry how im able to solve conflicting files?, should i do a pull request again? after fixing? 
its my first time doing pull request so >_<

**Comment by dr0pdb** [comment]
No, don't open a new PR. Learn it. 
Steps: 
1. Make sure you're in the root folder of the project.
2. git fetch upstream
3. make sure you're in the right branch i.e. Loggin-implementation
4. git rebase upstream/development
5. You will get a list of merge conflicts. Now leave the terminal as it is.
6. Open android studio and check the mentioned files(CodingCalendarAdapter.java, CodingCalendarHomeActivity.java) which have conflicts. Resolve them. 
7. now go back to the terminal and do a ```git add .```
8. Now ```git rebase --continue```
You've successfull resolved conflicts. Now push it to github using:
9. Now git push -f origin branch_name

Guide here - https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/#competing-line-change-merge-conflicts

In case of any issues, ask here.

**Comment by jafjdev** [comment]
Oh, sorry i just panicked and deleted the repo.. i think i'll need to do a new PR... @srv-twry .. ill close this one and reopen another.. right now.

**Pull request closed without merging**
