### PR TITLE
Fix #69 : Contest title not arranged properly in landscape mode

### LINKED ISSUE #69: Contest title not arranged properly in landscape mode
**Actual Behaviour**
Currently the contest title in the recycler view list item does not fit properly in the text view in landscape orientation. Also ellipsis does not appear in this case.

Screenshots for current behaviour : 
Portrait orientation : 
portrait_view

Landscape orientation : 
landscape_view_1

landscape_view_2

**Required behaviour** 
landscape_view_correct_1

landscape_view_correct_2 jpg

### PR DESCRIPTION
**Pull request by arundhatigupta**
Added necessary code to arrange the Contest title properly in the text view in
landscape orientation. Also added ellipsis at the end in the landscape mode.
Fix #69

### CODE REVIEW

**Comment by arundhatigupta** [comment]
@srv-twry  @mayank8318 please review.

**Comment by dr0pdb** [comment]
@arundhati24 Can you attach a screenshot ?

**Comment by srv-twry** [comment]
@arundhati24 Can you attach a screenshot ?

**Comment by arundhatigupta** [comment]
As attached in the issue #69 
Screenshots before modification :
landscape_view_1
landscape_view_2

Screenshots after modification :
landscape_view_correct_1
landscape_view_correct_2 jpg

**Comment by dr0pdb** [comment]
LGTM. :+1:

**Review by dr0pdb — APPROVED** [review]

**Comment by arundhati24** [comment]
Should we wait for mayank too or should I merge it? :smiley:

**Comment by dr0pdb** [comment]
@arundhati24 
I merged it. It's just a UI change not a big risk. :+1: 
Side note: Let's not work on Coding calendar now. Let's try to build other features.
BDW do you know how to use ROOM ?

**Comment by arundhatigupta** [comment]
@srv-twry  I know about it but have not used it. But Room and ViewModel would be a good option to use and I too am planning to use it in another project as well. So, will have to go through the documentation.

**Comment by arundhatigupta** [comment]
@srv-twry  I had not seen that you've already merged it! :smile:

**Comment by arundhatigupta** [comment]
@srv-twry 
Also, for the Lost and Found feature, we would require a storage i.e. a kind of database where we could keep track of lost and found items and that should sync through various devices. So, what is the backend that we shall use?

**Comment by dr0pdb** [comment]
That would require a backend server. We don't have it right now.
I'll create an issue for the roadmap of the project and then we can discuss there.

**Comment by arundhatigupta** [comment]
One more thing @srv-twry 
Let's use wiki rather than README for road map and separate features so that we or anyone checking out our project can refer to it whenever needed.

**Pull request merged**
