### PR TITLE
Fixed #49 Added a mention about the design pattern followed

### LINKED ISSUE #49: Add information about used architecture in the README.
Now that we are going to follow MVVM architecture, we should specifically mention it in the project's README.

### PR DESCRIPTION
**Pull request by sank20**
Fixes #49 

Changes: Added a sentence mentioning that the project follows the MVVM design pattern. Added a hyperlink to a Medium blog post about MVVM pattern.

### CODE REVIEW

**Comment by dr0pdb** [comment]
Hi @sank20, thanks for the PR.
I believe adding a Medium blog post is not good enough. I would suggest you to change the link to the official architecture guide: https://developer.android.com/jetpack/docs/guide

**Review by dr0pdb — CHANGES_REQUESTED** [review]
^ above comment.

**Comment by dr0pdb** [comment]
Also don't add it in the brief description of the app.
Add it along with the contributing guidelines line i.e. after the below line.
```
 ## Contributing
 Read the [Contributing guidelines](CONTRIBUTING.md) to get started.
```

**Comment by sank20** [comment]
@srv-twry Sure thing, makes sense. Adding the changes.

**Review by dr0pdb — APPROVED** [review]

**Pull request merged**
